### ISSUE TITLE
Module is not working on HyperOS (1.0.3.0 Android 14)

### ISSUE THREAD

**Issue by MrRazor** [j-hc/FlagSecurePatcher#10]
Module is not working on HyperOS. It is installed correctly after applying [https://github.com/j-hc/FlagSecurePatcher/pull/9](https://github.com/j-hc/FlagSecurePatcher/pull/9).

It looks like Xiaomi is doing something different. When I used this LSPosed module [https://github.com/LSPosed/DisableFlagSecure](https://github.com/LSPosed/DisableFlagSecure) it was working correctly. 
They are doing some special magic for HyperOS Android 14:
[https://github.com/LSPosed/DisableFlagSecure/blob/fd0b56f651810a2ed0268e639279c385f4425165/app/src/main/java/io/github/lsposed/disableflagsecure/DisableFlagSecure.java#L57](https://github.com/LSPosed/DisableFlagSecure/blob/fd0b56f651810a2ed0268e639279c385f4425165/app/src/main/java/io/github/lsposed/disableflagsecure/DisableFlagSecure.java#L57)
[https://github.com/LSPosed/DisableFlagSecure/blob/fd0b56f651810a2ed0268e639279c385f4425165/app/src/main/resources/META-INF/xposed/scope.list](https://github.com/LSPosed/DisableFlagSecure/blob/fd0b56f651810a2ed0268e639279c385f4425165/app/src/main/resources/META-INF/xposed/scope.list)

[magisk_install_log_2024-08-04T20.33.20[1].log](https://github.com/user-attachments/files/16488616/magisk_install_log_2024-08-04T20.33.20.1.log)

**Comment by j-hc** [comment]
upload the fw.zip to google drive and link it here after executing this command in termux

`pkg install zip && cd /system/framework/ && su -c $(command -v zip) -r9 /sdcard/fw.zip .`

**Comment by MrRazor** [comment]
Here it is: [fw.zip](https://drive.google.com/file/d/1JGY35QtvrMMQ_UcwtXtM89LhGE0PI50k/view?usp=drive_link)

**Comment by MrRazor** [comment]
also uploading zip of /system_ext/framework: [fw_ext.zip](https://drive.google.com/file/d/1JHTK-zl_w2Moef1LKuCrrAJygptZ0QJR/view?usp=sharing) - there is miui-services.jar, where is method notAllowCaptureDisplay, which returns boolean (we need false?) used in services.jar.

**Comment by j-hc** [comment]
Does this work?

[flag-secure-patcher-r12.zip](https://github.com/user-attachments/files/16570430/flag-secure-patcher-r12.zip)

**Comment by MrRazor** [comment]
Still not working, miui-services.jar is patched, but screenshot still cannot be captured.
[magisk_install_log_2024-08-11T10.21.48.log](https://github.com/user-attachments/files/16573138/magisk_install_log_2024-08-11T10.21.48.log)

**Comment by MrRazor** [comment]
It is working after manual fix - system_ext ($MODPATH/system_ext) folder from $MODPATH needs to be moved into system in $MODPATH ($MODPATH/system/system_ext). Also oat files of miui-services.jar needs to be stored in system_ext, not system ($MODPATH/system/system_ext/framework/oat/arm64/ miui-services.odex and miui-services.vdex ... i deleted miui-services.art because it is not used in original system_ext)

**Comment by MrRazor** [comment]
Also FlagSecureDetector (from 5ec1cff - https://t.me/real5ec1cff/211 ) detects something abnormal 

![Screenshot_2024-08-11-13-12-06-700_io github a13e300 dsf_detector](https://github.com/user-attachments/assets/ba30ddb0-5215-4f83-a726-5ff1431cbe59)

**Comment by j-hc** [comment]
[flag-secure-patcher-r12.zip](https://github.com/user-attachments/files/16573484/flag-secure-patcher-r12.zip)
how about this one

**Comment by j-hc** [comment]
[flag-secure-patcher-r12.zip](https://github.com/user-attachments/files/16573555/flag-secure-patcher-r12.zip)
how about this one

**Comment by MrRazor** [comment]
It failed during installation: [magisk_install_log_2024-08-11T14.13.35.log](https://github.com/user-attachments/files/16573668/magisk_install_log_2024-08-11T14.13.35.log)

But I found /system_ext is mounted on /system/system_ext... so in first first zip (https://github.com/j-hc/FlagSecurePatcher/issues/10#issuecomment-2282223433) i now changed path from /system_ext/miui-services.jar to /system/system_ext/miui-services and it is working same as here: https://github.com/j-hc/FlagSecurePatcher/issues/10#issuecomment-2282720208, and FlagSecureDetector still showing abnormal: https://github.com/j-hc/FlagSecurePatcher/issues/10#issuecomment-2282722458

**Comment by j-hc** [comment]
[flag-secure-patcher-r12.zip](https://github.com/user-attachments/files/16573675/flag-secure-patcher-r12.zip)
should be fine now

**Comment by MrRazor** [comment]
Still not working

[magisk_install_log_2024-08-11T14.39.07.log](https://github.com/user-attachments/files/16573691/magisk_install_log_2024-08-11T14.39.07.log)

**Comment by j-hc** [comment]
new one
[flag-secure-patcher-r12.zip](https://github.com/user-attachments/files/16573727/flag-secure-patcher-r12.zip)

**Comment by j-hc** [comment]
new one
[flag-secure-patcher-r12.zip](https://github.com/user-attachments/files/16573772/flag-secure-patcher-r12.zip)

**Comment by j-hc** [comment]
new one
[flag-secure-patcher-r12.zip](https://github.com/user-attachments/files/16573809/flag-secure-patcher-r12.zip)

**Comment by MrRazor** [comment]
Installation works, and can take screenshots. FlagSecureDetector still abnormal

https://github.com/user-attachments/assets/aebf5a0f-1f37-443c-8c5e-1bd58fa31d1b

**Comment by j-hc** [comment]
that doesnt matter. virtually no app tries to detect that.
