### ISSUE TITLE
Failing on installation on (A15)

### ISSUE THREAD

**Issue by soumyadip69** [j-hc/FlagSecurePatcher#13]
** A15**
Here is the error log:----

Archive:  /data/user/0/me.weishu.kernelsu/cache/module.zip
  inflating: customize.sh
- Extracting module files
Archive:  /data/user/0/me.weishu.kernelsu/cache/module.zip
   creating: util/
  inflating: util/paccer.jar
  inflating: util/dexlib2.jar
   creating: util/lib/
   creating: util/lib/arm64/
  inflating: util/lib/arm64/libandroid-cutils.so
  inflating: util/lib/arm64/libbz2.so.1.0.8
  inflating: util/lib/arm64/libz.so.1
  inflating: util/lib/arm64/libandroid-support.so
  inflating: util/lib/arm64/libandroid-ziparchive.so
  inflating: util/lib/arm64/libc++_shared.so
  inflating: util/lib/arm64/libz.so.1.3.1
  inflating: util/lib/arm64/libandroid-utils.so
  inflating: util/lib/arm64/libzopflipng.so
  inflating: util/lib/arm64/libbz2.so
  inflating: util/lib/arm64/libz.so
  inflating: util/lib/arm64/libandroid-base.so
  inflating: util/lib/arm64/libzopfli.so
  inflating: util/lib/arm64/libbz2.so.1.0
   creating: util/lib/x64/
  inflating: util/lib/x64/libandroid-cutils.so
  inflating: util/lib/x64/libbz2.so.1.0.8
  inflating: util/lib/x64/libz.so.1
  inflating: util/lib/x64/libandroid-support.so
  inflating: util/lib/x64/libandroid-ziparchive.so
  inflating: util/lib/x64/libc++_shared.so
  inflating: util/lib/x64/libz.so.1.3.1
  inflating: util/lib/x64/libandroid-utils.so
  inflating: util/lib/x64/libzopflipng.so
  inflating: util/lib/x64/libbz2.so
  inflating: util/lib/x64/libz.so
  inflating: util/lib/x64/libandroid-base.so
  inflating: util/lib/x64/libzopfli.so
  inflating: util/lib/x64/libbz2.so.1.0
   creating: util/lib/arm/
  inflating: util/lib/arm/libandroid-cutils.so
  inflating: util/lib/arm/libbz2.so.1.0.8
  inflating: util/lib/arm/libz.so.1
  inflating: util/lib/arm/libandroid-support.so
  inflating: util/lib/arm/libandroid-ziparchive.so
  inflating: util/lib/arm/libc++_shared.so
  inflating: util/lib/arm/libz.so.1.3.1
  inflating: util/lib/arm/libandroid-utils.so
  inflating: util/lib/arm/libzopflipng.so
  inflating: util/lib/arm/libbz2.so
  inflating: util/lib/arm/libz.so
  inflating: util/lib/arm/libandroid-base.so
  inflating: util/lib/arm/libzopfli.so
  inflating: util/lib/arm/libbz2.so.1.0
   creating: util/lib/x86/
  inflating: util/lib/x86/libandroid-cutils.so
  inflating: util/lib/x86/libbz2.so.1.0.8
  inflating: util/lib/x86/libz.so.1
  inflating: util/lib/x86/libandroid-support.so
  inflating: util/lib/x86/libandroid-ziparchive.so
  inflating: util/lib/x86/libc++_shared.so
  inflating: util/lib/x86/libz.so.1.3.1
  inflating: util/lib/x86/libandroid-utils.so
  inflating: util/lib/x86/libzopflipng.so
  inflating: util/lib/x86/libbz2.so
  inflating: util/lib/x86/libz.so
  inflating: util/lib/x86/libandroid-base.so
  inflating: util/lib/x86/libzopfli.so
  inflating: util/lib/x86/libbz2.so.1.0
   creating: util/bin/
   creating: util/bin/arm64/
  inflating: util/bin/arm64/zipalign
  inflating: util/bin/arm64/zip
   creating: util/bin/x64/
  inflating: util/bin/x64/zipalign
  inflating: util/bin/x64/zip
   creating: util/bin/arm/
  inflating: util/bin/arm/zipalign
  inflating: util/bin/arm/zip
   creating: util/bin/x86/
  inflating: util/bin/x86/zipalign
  inflating: util/bin/x86/zip
  inflating: uninstall.sh
  inflating: module.prop
  inflating: customize.sh
[+] Extracting services
[+] Patching
[+] Patched: notifyScreenshotListeners
[+] Patched: isSecureLocked
[+] Zipaligning
[+] Optimizing
dex2oat failed.
--------- beginning of main
12-06 19:44:49.758  8176  8176 W dex2oat : Mismatch between dex2oat instruction set features to use (ISA: Arm64 Feature string: a53,crc,-lse,-fp16,-dotprod,-sve) and those from CPP defines (ISA: Arm64 Feature string: -a53,crc,-lse,fp16,dotprod,-sve) for the command line:
12-06 19:44:49.758  8176  8176 W dex2oat : dex2oat --dex-file=/data/adb/modules_update/flagsecurepatcher/system/framework/services.jar --android-root=/system --instruction-set=arm64 --oat-file=/data/adb/modules_update/flagsecurepatcher/system/framework/oat/arm64/services.odex --app-image-file=/data/adb/modules_update/flagsecurepatcher/system/framework/oat/arm64/services.art --no-generate-debug-info --generate-mini-debug-info
12-06 19:44:49.758  8176  8176 I dex2oat : dex2oat --dex-file=/data/adb/modules_update/flagsecurepatcher/system/framework/services.jar --android-root=/system --oat-file=/data/adb/modules_update/flagsecurepatcher/system/framework/oat/arm64/services.odex --app-image-file=/data/adb/modules_update/flagsecurepatcher/system/framework/oat/arm64/services.art --no-generate-debug-info --generate-mini-debug-info --compiler-filter=speed
12-06 19:44:49.759  8176  8176 E dex2oat : Failed to open dex file '/data/adb/modules_update/flagsecurepatcher/system/framework/services.jar': Unable to open '/data/adb/modules_update/flagsecurepatcher/system/framework/services.jar!classes3.dex' : Header size is 112 but 120 was expected
12-06 19:44:49.786  8176  8176 I dex2oat : dex2oat took 30.105ms (5.383ms cpu) (threads: 8) 
sh: /data/adb/modules_update/flagsecurepatcher/customize.sh: line 52: 1: parameter not set
- Error: Failed to install module script
Error: Failed to install module script

**Comment by j-hc** [comment]
https://github.com/j-hc/FlagSecurePatcher/issues/11
