### ISSUE TITLE
Not working on HyperOS 1.0.2

### ISSUE THREAD

**Issue by HassanSardar** [j-hc/FlagSecurePatcher#4]
Hi, this doesn't seem to be working with A14 HyperOS 1.0.2
I'm attaching the fw.zip from my rom, as you asked in a previous issue. 
https://drive.google.com/file/d/1WDsaJCy1NE_rgpO7sGOyPWbWfoXu0vc6/view?usp=drivesdk

For ref: Tested on both Chrome Incognito and banking app

A huge thanks for the module and your time

**Comment by j-hc** [comment]
can you send the flash logs

**Comment by HassanSardar** [comment]
Sorry for getting back late, didn't get the notification. 
The flash log is attached below. 
Let me know if you need any other logs
[magisk_install_log_2024-06-09T15.54.37.log](https://github.com/user-attachments/files/15752768/magisk_install_log_2024-06-09T15.54.37.log)

**Comment by HassanSardar** [comment]
I was previously using Zygisk Assistant, yes. 
So I clean flashed the firmware and tested it with just this module and Magisk. Same result. Screenshots still don't go through

**Comment by HassanSardar** [comment]
Let me know if I can help with any other info. I will be more than happy for any other logs and testing

**Comment by j-hc** [comment]
the fw.zip you first sent is after the module is flashed. i need it without flagsecurepatcher flashed.

**Comment by j-hc** [comment]
you can try r10
