### ISSUE TITLE
Causes a bootloop on the June pixel update 

### ISSUE THREAD

**Issue by ndv400** [j-hc/FlagSecurePatcher#5]
Pixel 6a, after OTA updating to 14.0.0 (AP2A.240605.024, Jun 2024) from 14.0.0 (AP1A.240305.019.A1, Mar 2024), my phone entered a bootloop with this module on. 
Took a while to figure out it was this module, don't have any logs because it straight up hangs on the logo. 
Worked fine on the March update.

**Comment by j-hc** [comment]
tried reflashing?

**Comment by ndv400** [comment]
Yeah, first thing I tried. No matter what I do, can't get it past the logo if I have FlagSecurePatcher enabled.

**Comment by j-hc** [comment]
run this in termux and upload the fw.zip here. it can be large, you can use google drive etc.
`pkg install zip && cd /system/framework/ && su -c $(command -v zip) -r9 /sdcard/fw.zip .`

**Comment by ndv400** [comment]
[Sure](https://drive.google.com/file/d/181qrIhJrn2rDYURbhUJbnPFQQWT-EDi-/view?usp=drivesdk)

**Comment by j-hc** [comment]
everything looks fine. even if the reason is FlagSecurePatcher, you should be able to grab a logcat before the it reboots with adb

**Comment by ndv400** [comment]
Sure, I just ran adb logcat > logcat.txt three times. 
First run, successful boot to lockscreen with all magisk modules disabled: 
[logcat-good.txt](https://github.com/user-attachments/files/15944857/logcat-good.txt)
Second run, bootloop just with FlagSecurePatcher enabled and everything else disabled: 
[logcat-bad.txt](https://github.com/user-attachments/files/15944860/logcat-bad.txt)
Third run, just in case, same conditions as previously (just with FlagSecurePatcher enabled and everything else disabled): 
[logcat.txt](https://github.com/user-attachments/files/15944865/logcat.txt)

**Comment by j-hc** [comment]
before reflashing did you make sure you uninstalled the module and rebooted? reflashing while its disabled wont work

**Comment by ndv400** [comment]
Yeah, I did. Well, so far everything works if I just keep FlagSecurePatcher disabled

**Comment by j-hc** [comment]
try r9

**Comment by j-hc** [comment]
try r10

**Comment by ndv400** [comment]
Thanks, works as intended now!
