### ISSUE TITLE
last version is dangerous 

### ISSUE THREAD

**Issue by DarkPhilosophy** [j-hc/FlagSecurePatcher#6]
Generated by AppErrorsTracking 1.3(6)
Project URL: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: nubia
[Device Model]: NX769J
[Display]: REDMAGICOS9.0.11_NX769J_EEA
[Android Version]: 14
[Android API Level]: 34
[System Locale]: en_US
[Process ID]: 15412
[User ID]: 0
[CPU ABI]: none
[Package Name]: com.android.imsserviceentitlement
[Version Name]: 14
[Version Code]: 34
[Target SDK]: 34
[Min SDK]: 34
[Error Type]: Native
[Crash Time]: 2024-06-25T17:39:54.492
[Stack Trace]:
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'nubia/NX769J-EEA/NX769J:14/UKQ1.230917.001/20240402.022722:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2024-06-25 17:39:54.310394363+0300
Process uptime: 1s
Cmdline: zygote64
pid: 15412, tid: 15418, name: viceentitlement  >>> zygote64 <<<
uid: 10326
tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
pac_enabled_keys: 000000000000000f (PR_PAC_APIAKEY, PR_PAC_APIBKEY, PR_PAC_APDAKEY, PR_PAC_APDBKEY)
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000006fa220ec50
    x0  0000006fa2413c98  x1  000000000000000b  x2  00000072d392eda0  x3  00000072d392ee20
    x4  b400007114e28140  x5  0000000000000004  x6  0000000000000a6e  x7  7f7f7f7f7f7f7f7f
    x8  6867e4656afc2524  x9  6867e4656afc2524  x10 00000072d4449040  x11 0000000000000000
    x12 0000000000000000  x13 0000000000040010  x14 0000000000000002  x15 0000000000000030
    x16 00000072c4fb5268  x17 0000007298b88358  x18 0000006f7481e000  x19 00000072d392ee20
    x20 00000072d392eda0  x21 000000000000000b  x22 0000000000000001  x23 00000072c4fb7000
    x24 00000072c4fb79e0  x25 00000072d4449000  x26 0000006fa220e000  x27 00000072c4fb79b0
    x28 00000072c4fb6748  x29 00000072d392ec90
    lr  00000072c4fb12b8  sp  00000072d392eb60  pc  0000006fa1b7a684  pst 0000000060001000
10 total frames
backtrace:
      #00 pc 000000000037a684  /apex/com.android.art/lib64/libart.so (art::FaultManager::HandleSigsegvFault(int, siginfo*, void*)+56) (BuildId: ddcc440d4609d2099db9d20895487a78)
      #01 pc 00000000000022b4  /apex/com.android.art/lib64/libsigchain.so (art::SignalChain::Handler(int, siginfo*, void*)+552) (BuildId: f2b3263de725c113909612342846664c)
      #02 pc 0000000000000860  [vdso]
      #03 pc 0000000000813910  /apex/com.android.art/lib64/libart.so (BuildId: ddcc440d4609d2099db9d20895487a78)
      #04 pc 000000000039f448  /apex/com.android.art/lib64/libart.so (art::Thread::Thread(bool)+188) (BuildId: ddcc440d4609d2099db9d20895487a78)
      #05 pc 00000000003c7600  /apex/com.android.art/lib64/libart.so (art::Thread* art::Thread::Attach<art::Thread::Attach(char const*, bool, _jobject*, bool, bool)::$_0>(char const*, bool, art::Thread::Attach(char const*, bool, _jobject*, bool, bool)::$_0, bool) (.__uniq.112444171608964125319761912539055931073.llvm.15810765920626467746)+156) (BuildId: ddcc440d4609d2099db9d20895487a78)
      #06 pc 00000000003c6f80  /apex/com.android.art/lib64/libart.so (art::Runtime::AttachCurrentThread(char const*, bool, _jobject*, bool, bool)+132) (BuildId: ddcc440d4609d2099db9d20895487a78)
      #07 pc 00000000005a5460  /apex/com.android.art/lib64/libart.so (art::ThreadPoolWorker::Callback(void*)+124) (BuildId: ddcc440d4609d2099db9d20895487a78)
      #08 pc 00000000000c368c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208) (BuildId: 205b2a611ad35e86e866aac2abcf62e1)
      #09 pc 000000000005cfa4  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68) (BuildId: 205b2a611ad35e86e866aac2abcf62e1)

**Comment by j-hc** [comment]
whats the issue? crashes? bootloop? logcat and tombstone?

**Comment by DarkPhilosophy** [comment]
Crash after updating your module and booting device an internal app called **com.android.imsserviceentitlement** just crashed, it didn't happen previously on R8, the error log posted above is generated from a Xposed module called AppErrorsTracking.

**Comment by j-hc** [comment]
still need to see the logcat and crash tombstone.
and can you run this in termux, upload the fw.zip and link it here 
`pkg install zip && cd /system/framework/ && su -c $(command -v zip) -r9 /sdcard/fw.zip .`

**Comment by DarkPhilosophy** [comment]
Seems is work fine now, it only happened once exactly after upgrading still if it happens again or anything else in that matter I'll let you know. I also use lots of module and the error might be related to Zygisk Assistance, I notice in last version Magisk 27003 things tend to break
