### ISSUE TITLE
Boot loop when Bluetooth enabled 

### ISSUE THREAD

**Issue by 5a9awneh** [j-hc/FlagSecurePatcher#7]
System goes into 5 short boot loops when Bluetooth is on, then performs a full reboot, back to first unlock screen

**Comment by 5a9awneh** [comment]
Yes indeed I did, issue only occurs when FlagSecurePatcher is Enabled


________________________________

**Comment by j-hc** [comment]
need to see the fw.zip from this command

`pkg install zip && cd /system/framework/ && su -c $(command -v zip) -r9 /sdcard/fw.zip .`

**Comment by 5a9awneh** [comment]
[fw.zip](https://ufile.io/qxoe1rir)

**Comment by j-hc** [comment]
> [fw.zip](https://ufile.io/qxoe1rir)

you might wanna use google drive

**Comment by 5a9awneh** [comment]
Great idea, thanks! 
[fw.zip](https://drive.google.com/file/d/10MKRwuJoQ8IgnHxO4UlGKQELFv0H--X-/view?usp=drivesdk)

**Comment by 5a9awneh** [comment]
@j-hc is this fixed in r13?

**Comment by j-hc** [comment]
probably not but you can try.

im assuming this happens due to a bug in dexlib2 that results in non-identical dex after re-assembling. so there is not much i can do.

**Comment by 5a9awneh** [comment]
Just tested it, works fine now. Thanks! 

![works-doesnt-work](https://github.com/user-attachments/assets/c23aec0a-6986-4234-824d-c8c446e6fd10)
![maxresdefault-1](https://github.com/user-attachments/assets/00f9f2e8-95fb-4009-b1bf-75330b32ba44)
